### ISSUE TITLE
compatibility with yaml file and swagger

### ISSUE THREAD

**Issue by aurelBZH** [sfu-ireceptor/API#6]
Hi, 
i started to dive in the project and want to have information on the API. I try all the yaml file in swagger but add error message. Maybe you can add in the documentation that only iReceptor_Data_Service_API_V2.yaml is compatible with swagger 

thanks 

Aurélien 
bioinformatician
U959 (INSERM/SU)
Hôpital de la Pitié-Salpêtrière

**Comment by bcorrie** [comment]
Hi Aurelien,

Thanks for pointing out the clarification, I have made a change to fix the issue. Sorry for the confusion.

Brian
